on:
  # pull_request:
  #   types:
  #     - closed
  #   paths:
  #     - 'src/**/*.py'  
  #     - 'requirements.txt' 
  #     - 'build_script.py' 
  #     - '.github/workflows/build.yaml' 
  #     - 'assets/**'
  push:
    branches:
      - 'release/*'
      - 'main'

jobs:
  build-game:
    if: (github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')))
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Extract Version
        id: extract_version
        run: |
          VERSION=$(grep '^version = ' pyproject.toml | cut -d '"' -f 2)
          if [ -z "$VERSION" ]; then echo "Error: Version not found"; exit 1; fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build with PyInstaller
        run: python build_script.py

      - name: Create Professional DMG
        run: |
          brew install create-dmg

          echo "Current directory: $(pwd)"
          ls -R assets/

          # 创建打包根目录
          mkdir -p dist/dmg_root
          cp -r dist/AngryBirdsWatermelon.app dist/dmg_root/
          
          # 创建 DMG，关联根目录下的 assets/dmg_background.png
          create-dmg \
            --volname "AngryBirds Installer" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon-size 100 \
            --background "assets/dmg_background.png" \
            --icon "AngryBirdsWatermelon.app" 200 190 \
            --app-drop-link 400 190 \
            --hide-extension "AngryBirdsWatermelon.app" \
            "AngryBirdsWatermelon-${{ env.VERSION }}.dmg" \
            "dist/dmg_root/"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AngryBirds-Test-Build
          path: AngryBirdsWatermelon-${{ env.VERSION }}.dmg

      - name: Release
        # 确保只在 main 或 release 分支触发
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
        uses: softprops/action-gh-release@v1
        with:
          # 使用 version.toml 里的版本号，前面加 v
          tag_name: v${{ env.VERSION }}
          # 标题也显示版本号
          name: "Release v${{ env.VERSION }}"
          # 确保文件名与你前面生成的动态文件名一致
          files: AngryBirdsWatermelon-${{ env.VERSION }}.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}